In [1]:
import matplotlib.pyplot as plt
import numpy as np


[[1, 1, 1], [0, 1, 0], [1, 0, 0], [0, 0, 0]]

In [ ]:
def notAnd(a,b):
    return not(a and b) 

      
def Or(a,b):
    return (a or b)

def neural(a,b):
    return (Or(a,b) and notAnd(a,b))


print(neural(0,1))

In [7]:
def sigmoide(z) :
   
    return 1/(1+np.exp(-z))
class Neural:
    def __init__(self, x,y,layer1=2,layer2=1):
        self.x = np.c_[ x, np.ones(len(x)) ]
        self.y = y
        self.Z1=0
        self.Z2=0
      
        
        self.layer1=0
        self.layer2=0
        
        self.neurone_layer1=layer1
        self.neurone_layer2=layer2
      
        
        self.theta_layer0=np.random.rand(self.x.shape[1],self.neurone_layer1)
        self.theta_layer1=np.random.rand(self.neurone_layer1+1,self.neurone_layer2)
        
    def forward(self) :
        self.Z1=self.x @ self.theta_layer0
        self.layer1=sigmoide(self.Z1)
        self.layer1=np.c_[ self.layer1, np.ones(len(self.layer1)) ]
        self.Z2=self.layer1 @ self.theta_layer1
        self.layer2=sigmoide(self.Z2) 
      #  self.layer2=np.c_[ self.layer2, np.ones(len(self.layer2)) ]


    
    def bark(self):
        print("Woof!")



In [8]:
x=np.array(([1,1],[1,0],[0,1],[0,0]))
y=np.array(([0],[1],[1],[0]))
n=Neural(x,y)
n.forward()
print(n.Z1)
print(n.layer1)
print("*********************")
print(n.Z2)
print(n.layer2)


[[1.27431888 0.77457172]
 [0.40184795 0.20062364]
 [1.0164716  0.69939181]
 [0.14400068 0.12544372]]
[[0.78148117 0.68450902 1.        ]
 [0.59913157 0.54998835 1.        ]
 [0.73428474 0.66805291 1.        ]
 [0.53593809 0.53131987 1.        ]]
*********************
[[1.10314956]
 [1.03008761]
 [1.08774452]
 [1.01010354]]
[[0.75084977]
 [0.73693288]
 [0.74795676]
 [0.73304041]]
